services:

  registration:
  build:
    context: ./Registration
    dockerfile: Dockerfile
    container_name: registration-service
    ports:
      - "6001:5001"
    env_file:
      - ./Registration/.env

  login:
    build:
      context: ./Login
      dockerfile: Dockerfile
    container_name: login-service
    ports:
      - "6002:5002"
    env_file:
      - ./Login/.env